name: noise2
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - cudatoolkit
  - jupyter
  - cloudpickle
  - pycocotools
  - pytorch-cuda==12.4
  - python==3.11
  - pytorch==2.5.1
  - torchvision==0.20.1
  - torchmetrics==1.3.1
  - numpy==1.26.4
  - pillow==11.1.0
  - tqdm==4.66.2
  - matplotlib==3.10.0
  - seaborn==0.13.2
  - scikit-learn==1.6.0
  - pandas
