channels:
  - rocketce
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=2.0.2
  - scipy=1.14.1
  - scikit-learn=1.5.2
  - ipython=8.23.0
  - jupyter
  - gdown
  - nbconvert=7.16.3
  - ipykernel=6.29.4
  - cloudpickle

