channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python==3.11
  - cudatoolkit
  - jupyter
  - pycocotools==2.0.8
  - pytorch-lightning==2.5.0.post0
  - pytorch==2.3.1
  - torchvision==0.18.1
  - torchmetrics==1.3.1
  - numpy==1.26.4
  - pillow==10.2.0
  - tqdm==4.66.2
  - matplotlib==3.8.3
  - seaborn==0.13.2
  - cloudpickle==3.1.1
